services:
  qiraati-webapp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - "3000:80"  # Map host port 3000 to container port 80
    restart: unless-stopped
    networks:
      - qiraati-network
    labels:
      - "com.docker.compose.service=qiraati-webapp"
    # Development-specific settings
    volumes:
      - ./src:/app/src:ro  # Mount source code for hot reload (read-only)
    # Disable health check sementara untuk debugging
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost/"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s

  # Backend API proxy (REQUIRED for Quran & Prayer Times)
  qiraati-api:
    build:
      context: ./backend-example
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - "3001:3001"  # Map host port 3001 to container port 3001
    restart: unless-stopped
    networks:
      - qiraati-network
    depends_on:
      - qiraati-webapp
    # Development-specific settings
    volumes:
      - ./backend-example:/app:ro  # Mount backend code for hot reload (read-only)

networks:
  qiraati-network:
    driver: bridge

# Optional: Volume untuk persistent data jika diperlukan
# volumes:
#   qiraati-data: 